version: "3.8"

services:
  backend:
    build: ./Clothing
    ports:
      - "8080:8080"
    env_file:
      - .env

  frontend:
    build:
      context: ./clothing-store-frontend
      args: # Pass as build ARG (not runtime env)
        VITE_API_BASE: http://localhost:8080/api
    ports:
      - "5173:80"
    depends_on:
      - backend
